headers = {
    "User-Agent": (
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
        "AppleWebKit/537.36 (KHTML, like Gecko) "
        "Chrome/125.0.0.0 Safari/537.36"
    ),
    "Accept": "application/json, text/javascript, */*; q=0.01",
    "Accept-Language": "en-US,en;q=0.9",
    "Referer": "https://finance.yahoo.com/",
    "Cookie": "GUCS=AQXCfRV1; A3=d=AQABBKGKc2cCEHT7atMqsTimn1z_h2DE9DgFEgABCAG-ZmiWaF5EyyMA9qMCAAcIdFG_ZgcRnMQ&S=AQAAAhI85Rn162FjBhJVZVHLEzg; GUC=AQABCAFoZr5olkIc-wSJ&s=AQAAAIdHtF0U&g=aGVycQ; A1S=d=AQABBKGKc2cCEHT7atMqsTimn1z_h2DE9DgFEgABCAG-ZmiWaF5EyyMA9qMCAAcIdFG_ZgcRnMQ&S=AQAAAhI85Rn162FjBhJVZVHLEzg; EuConsent=CQT7KEAQT7KEAAOACBHEBxFoAP_gAEPgACiQKptB9G7WTXFneTp2YPskOYwX0VBJ4MAwBgCBAUABzBIUIBwCVmAzJEyIICACGAIAIGBBIABtGAhAQEAAYIAFAABIAEgAIBAAIGAAACAAAABACAAAAAAAAAAQgEAXMBQgmCYEBFoIQUhAggAgAQAAAAAEAIgBCAQAEAAAQAAACAAIACgAAgAAAAAAAAAEAFAIEAAAIAECAgvkdAAAAAAAAAAIAAYACAABAAAAAIKpgAkGhUQRFgQAhEIGEECAAQUBABQIAgAACBAAAATBAUIAwAVGAiAEAIAAAAAAAAAAABAAABAAhAAEAAQIAAAAAIAAgAIAAAACAAAAAAAAAAAAAAAAAAAAAAAAAGIBAggCAABBAAQUAAAAAgAAAAAAAAAIgACAAAAAAAAAAAAAAIgAAAAAAAAAAAAAAAAAAIEAAAIAAAAoDEFgAAAAAAAAAAAAAACAABAAAAAIAAA; A1=d=AQABBKGKc2cCEHT7atMqsTimn1z_h2DE9DgFEgABCAG-ZmiWaF5EyyMA9qMCAAcIdFG_ZgcRnMQ&S=AQAAAhI85Rn162FjBhJVZVHLEzg; cmp=t=1751478890&j=1&u=1---&v=87; axids=gam=y-ZXW.GtdE2uIcKMnJTlVCAkYz_ZrV42oj~A&dv360=eS00QXB3bmd4RTJ1Rzg5alBpbmxETG83MnRHa3JOZEdWVX5B&ydsp=y-YdyE4LNE2uKrZBVA1MkZ_6SQXDAUX2eM~A&tbla=y-YA.WjD9E2uJ5v8dqu4d6y_zxH8rziNJW~A; tbla_id=e7fe438e-84c7-4cc2-917f-3b82510bda39-tuctf2f6fdb; PRF=t%3DPLTR%26dock-collapsed%3Dtrue"
}